version: '{build}'
os: Windows Server 2012
install:
  - ps: Install-Product node 12
  - cmd: choco install sbt --version 1.4.0 -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
build: off
test_script:
  - cmd: sbt ";test;scripted"
cache:
  - C:\sbt
  - C:\Users\appveyor\.ivy2\cache
  - C:\Users\appveyor\.sbt
